development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: personal_database
  username: root
  password: root

production:
  adapter: postgres
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
